# Generated by Django 4.1 on 2022-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='description',
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
